#+OPTIONS: toc:nil num:nil date:nil
*ALWAYS CHOOSE SLACKWARE LINUX*

Unless you are a consumer with expecations of one click and your computer works the way you dream it would, Slackare Linux is a fantastic distribution of gnu linux for both dekstops and for servers.  Slackware won Linux Questions' "Best Server Distro of the Year" poll! (  https://www.linuxquestions.org/questions/2020-linuxquestions-org-members-choice-awards-131/server-distribution-of-the-year-4175687344/)

* The reasons I always choose Slackware:
** Slackware succeeded where other distros failed.
   When I first tried gnu linux, back when I owned hardware with powerpc processors. Technically, it was Slackintosh, the port of Slackware to powerpc, that succeeded at getting all the hardware components working on its initial install without additional tweaking or hunting down firmware (audio, video, mouse, keyboard, x11, etc).  Before Slackintosh I had tried Mepis, OpenSuse, and Yellowdog (I was limited to distros that had powerpc ports).  I had planned on trying Gentoo after Slackinsosh, but since Slackintosh worked, I never got to it.  Eventually I replaced the powerpc machines with x86 machines, and migrated to Slackware 10.  I've been using Slackware since.
** Slackware's documentation
   When followed to the tee, it works!
** Slackware has stood the test of time:
   Even without corporate sponsors, Slackware linux remains the oldest distribution of gnu linux.  It is maintained by its creator, Pat Volkerding, with the help of just a handful of friends and comrades, and the support of a community of loyal slackware fans and users.  There must be something that we like about it for it still to be around forty years later.
** Slackware users are respectful.
   Slackware has a way, and we learn it.
** One subgenious > herd of geniuses
   One benevolent dictator (Pat) and his few chosen helpers do a better job, imho, at maintaining Slackware than distributions mired by large group politics.  Slackware's way has remained the same through the decades.  It is stable.
** Good for Learning Linux
   Although described as a distribution for advanced users, due to its clear documentation, imho it is also a fantastic distro for students of linux.
** Slackare IQ test:
   Slackware's installer requires typing commmands at a CLI prompt.  This bewilders users incapable of reading the clear documenation to learn the one command they need to type at the prompt: "setup".  It shouldn't be difficult to type "setup", however, whether ironic, or tragic, or tragically ironic, the need to read instructions weeds out the majority of distrohoppers. Reading the documentation is Slackware's first initiation ritual, followed by compiling packages from source code, and building a kernel.  These rituals keep slackware's user base erudite, with clever questions and clever responses populating the threads of slackware forums.  (In contrast, the forums of the one-click installbable distributions popularly recommended to new linux users,are populated with posts of noobs giving other noobs bad advice).
** Non-Corporate:
   Most of my work is in the non-profit sector.  I like to choose tools without eco/political ties or license requirements.  Of all the distributions of gnu linux, Slackware, without corporate sponsorship, shows the least greed.  How come paid developers at redhat and canonical cannot produce as solid of distributions as a single developer barely surviving off of contributions from loyal slackware fans and users?  Passion cannot be purchased.  Slackare users and developers love our slackware and are passionate about keeping it not just alive, but stable and adhering to the core slackware principles of keeping it simple, with configurations in text files that remain at the same paths, release after release.
** Funny:
   The Slackware Community has a sense of humor.  The dry, technical, and tedious aspect of learning computer science is always more palatable when enriched with humor, and most slackers are hilarious.
